name: Comment on label
on:
  issues:
    types:
      - labeled
jobs:
  patched:
    if: github.event.label.name == 'patched'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This issue is patched in recent commits, please wait for next release.

            > Please DO NOT close this issue, a bot will handle this automatically when new release drops.
